import type {
  DirectoryData,
  Organization,
  Program,
  ServiceLocation,
  ServiceMethod,
  Topic,
} from "./types.ts";

type ProgramSeed = {
  id: string;
  organization: string;
  providerType?: Organization["providerType"];
  name: string;
  description: string;
  topics: Topic[];
  methods?: ServiceMethod[];
  serviceArea?: string;
  eligibility?: string;
  ageRange?: string;
  languages?: string[];
  cost?: string;
  intake?: string;
  phone: string;
  website: string;
  emergency?: boolean;
};

const verifiedAt = "2026-08-16";

const seeds: ProgramSeed[] = [
  {
    id: "mb-211",
    organization: "211 Manitoba",
    name: "Community service navigation",
    description: "Confidential navigation to health, social, government and community services across Manitoba.",
    topics: ["Emergency / Crisis", "Food / Basic Needs", "Housing", "Health", "Income Support"],
    methods: ["Phone", "Online"],
    phone: "211",
    website: "https://mb.211.ca/",
  },
  {
    id: "health-links",
    organization: "Shared Health Manitoba",
    providerType: "Health authority",
    name: "Health Links – Info Santé",
    description: "24-hour nurse advice and guidance on where to seek care.",
    topics: ["Health", "Emergency / Crisis", "Older Adults", "Parenting"],
    methods: ["Phone"],
    phone: "204-788-8200",
    website: "https://sharedhealthmb.ca/patient-care/health-links-info-sante/",
    emergency: true,
  },
  {
    id: "crc-raam",
    organization: "Shared Health Manitoba",
    providerType: "Health authority",
    name: "Crisis Response Centre RAAM Clinic",
    description: "Rapid-access assessment, medication support and referrals for adults concerned about substance use.",
    topics: ["Mental Health / Addictions", "Health", "Emergency / Crisis"],
    phone: "204-792-7159",
    website: "https://sharedhealthmb.ca/services/mental-health/mha-services/where-can-i-find-a-raam-clinic/",
  },
  {
    id: "riverpoint-raam",
    organization: "Shared Health Manitoba",
    providerType: "Health authority",
    name: "River Point Centre RAAM Clinic",
    description: "Walk-in rapid-access addiction medicine, counselling, nursing and referrals.",
    topics: ["Mental Health / Addictions", "Health"],
    phone: "204-390-8078",
    website: "https://sharedhealthmb.ca/services/mental-health/mha-services/where-can-i-find-a-raam-clinic/",
  },
  {
    id: "ahwc-raam",
    organization: "Aboriginal Health and Wellness Centre",
    name: "Indigenous RAAM Clinic",
    description: "Culturally safe rapid-access addiction medicine and follow-up care.",
    topics: ["Mental Health / Addictions", "Health", "Indigenous"],
    phone: "204-560-7927",
    website: "https://sharedhealthmb.ca/services/mental-health/mha-services/where-can-i-find-a-raam-clinic/",
  },
  {
    id: "klinic-crisis",
    organization: "Klinic Community Health",
    name: "Crisis and suicide prevention support",
    description: "Confidential crisis counselling, suicide prevention and community health support.",
    topics: ["Mental Health / Addictions", "Emergency / Crisis", "Victim Support", "2SLGBTQ+"],
    methods: ["Phone", "In person"],
    phone: "204-786-8686",
    website: "https://klinic.mb.ca/crisis-support/",
    emergency: true,
  },
  {
    id: "mainstreet-shelter",
    organization: "Main Street Project",
    name: "Emergency shelter and drop-in",
    description: "Low-barrier daytime support and overnight shelter with food, showers, clothing and case workers.",
    topics: ["Homelessness", "Housing", "Food / Basic Needs", "Emergency / Crisis"],
    phone: "204-982-8267",
    website: "https://www.mainstreetproject.ca/programs-and-services/emergency-and-social-services/",
    emergency: true,
  },
  {
    id: "mainstreet-withdrawal",
    organization: "Main Street Project",
    name: "Men’s and non-binary withdrawal management",
    description: "Non-medical withdrawal management with meals, peer support, harm-reduction supplies and aftercare planning.",
    topics: ["Mental Health / Addictions", "Health", "Homelessness"],
    phone: "204-982-8251",
    website: "https://www.mainstreetproject.ca/programs-and-services/addictions-support-and-health/",
  },
  {
    id: "riverpoint-withdrawal",
    organization: "Main Street Project",
    name: "Women’s and non-binary withdrawal management",
    description: "Non-medical withdrawal management with health, cultural and recovery supports.",
    topics: ["Mental Health / Addictions", "Health", "Victim Support"],
    phone: "204-982-8222",
    website: "https://www.mainstreetproject.ca/programs-and-services/addictions-support-and-health/",
  },
  {
    id: "siloam",
    organization: "Siloam Mission",
    name: "Shelter and resource services",
    description: "Emergency shelter, meals, clothing, health supports and pathways toward stable housing.",
    topics: ["Homelessness", "Food / Basic Needs", "Housing", "Health"],
    phone: "204-956-4344",
    website: "https://www.siloam.ca/",
  },
  {
    id: "centre-hope",
    organization: "Salvation Army Winnipeg Centre of Hope",
    name: "Emergency and transitional shelter",
    description: "Emergency dorms, transitional rooms and housing-focused support for adults and families.",
    topics: ["Homelessness", "Housing", "Emergency / Crisis", "Food / Basic Needs"],
    phone: "204-946-9400",
    website: "https://tsasites.salvationarmy.ca/web/winnipeg-centre-of-hope/programs/programs-overview",
  },
  {
    id: "winnipeg-harvest",
    organization: "Harvest Manitoba",
    name: "Food assistance and food-bank referrals",
    description: "Food support, referrals to local food banks and community food programming.",
    topics: ["Food / Basic Needs", "Income Support", "Community and Culture"],
    phone: "204-982-3660",
    website: "https://www.harvestmanitoba.ca/need-food/",
  },
  {
    id: "meals-wheels",
    organization: "Meals on Wheels Winnipeg",
    name: "Home-delivered meals",
    description: "Nutritious meal delivery for people who cannot prepare or access meals independently.",
    topics: ["Older Adults", "Food / Basic Needs", "Accessibility", "Health"],
    phone: "204-956-7711",
    website: "https://www.mealswinnipeg.com/",
  },
  {
    id: "a-o-support",
    organization: "A & O: Support Services for Older Adults",
    name: "Older-adult information and support",
    description: "Information, counselling, safety, social engagement and housing supports for older adults.",
    topics: ["Older Adults", "Housing", "Health", "Community and Culture", "Victim Support"],
    phone: "204-956-6440",
    website: "https://www.aosupportservices.ca/",
  },
  {
    id: "rainbow-resource",
    organization: "Rainbow Resource Centre",
    name: "2SLGBTQ+ counselling and community programs",
    description: "Counselling, education, peer groups and community supports for 2SLGBTQ+ people and families.",
    topics: ["2SLGBTQ+", "Mental Health / Addictions", "Community and Culture", "Youth / Young Adults"],
    phone: "204-474-0212",
    website: "https://rainbowresourcecentre.org/",
  },
  {
    id: "sunshine-house",
    organization: "Sunshine House",
    name: "Drop-in and harm-reduction programs",
    description: "Participant-led drop-in, mobile overdose prevention and harm-reduction services.",
    topics: ["2SLGBTQ+", "Mental Health / Addictions", "Health", "Homelessness", "Indigenous"],
    methods: ["In person", "Mobile"],
    phone: "204-783-8565",
    website: "https://sunshinehousewpg.org/",
  },
  {
    id: "nine-circles",
    organization: "Nine Circles Community Health Centre",
    providerType: "Health authority",
    name: "Community health and drug checking",
    description: "HIV/STBBI care, testing, prevention, harm reduction and anonymous drug-checking services.",
    topics: ["Health", "Mental Health / Addictions", "2SLGBTQ+"],
    phone: "204-940-6000",
    website: "https://ninecircles.ca/",
  },
  {
    id: "manitoba-possible",
    organization: "Manitoba Possible",
    name: "Disability services and employment support",
    description: "Independent living, employment, communication and community participation services.",
    topics: ["Accessibility", "Employment / Training", "Community and Culture"],
    phone: "204-975-3010",
    website: "https://www.manitobapossible.ca/",
  },
  {
    id: "barrier-free",
    organization: "Barrier-Free Manitoba",
    name: "Accessibility advocacy",
    description: "Public-interest advocacy for the effective implementation of accessibility rights in Manitoba.",
    topics: ["Accessibility", "Legal Advocacy", "Community and Culture"],
    methods: ["Online"],
    phone: "204-291-6150",
    website: "https://barrierfreemb.com/",
  },
  {
    id: "credit-counselling",
    organization: "Credit Counselling Society",
    name: "Nonprofit debt counselling",
    description: "Confidential budgeting, credit and debt counselling available to Manitoba residents.",
    topics: ["Consumer Debt Services", "Income Support", "Education"],
    methods: ["Phone", "Online"],
    phone: "1-888-527-8999",
    website: "https://nomoredebts.org/canada-credit-counselling/manitoba/winnipeg",
  },
  {
    id: "seed-financial",
    organization: "SEED Winnipeg",
    name: "Financial empowerment and benefits access",
    description: "Benefits navigation, identification, money management, matched savings and business development.",
    topics: ["Consumer Debt Services", "Income Support", "Employment / Training", "Newcomers", "Indigenous"],
    phone: "204-927-9935",
    website: "https://seedwinnipeg.ca/",
  },
  {
    id: "legal-aid",
    organization: "Legal Aid Manitoba",
    providerType: "Government",
    name: "Legal assistance",
    description: "Legal representation for eligible people in criminal, family and certain civil matters.",
    topics: ["Legal Advocacy", "Victim Support", "Income Support"],
    phone: "204-985-8500",
    website: "https://www.legalaid.mb.ca/",
  },
  {
    id: "clea-law-phone",
    organization: "Community Legal Education Association",
    name: "Law Phone-In and Lawyer Referral",
    description: "General legal information and referrals to lawyers and community resources.",
    topics: ["Legal Advocacy", "Education", "Victim Support"],
    methods: ["Phone", "Online"],
    phone: "204-943-2305",
    website: "https://www.communitylegal.mb.ca/",
  },
  {
    id: "victim-services",
    organization: "Manitoba Justice Victim Services",
    providerType: "Government",
    name: "Victim Services",
    description: "Information, court support, safety planning and referrals for victims of crime.",
    topics: ["Victim Support", "Legal Advocacy", "Emergency / Crisis"],
    methods: ["Phone", "In person"],
    phone: "204-945-6851",
    website: "https://www.gov.mb.ca/justice/vs/",
  },
  {
    id: "willow-place",
    organization: "Willow Place",
    name: "Family violence shelter and support",
    description: "Confidential crisis support, shelter and family-violence services.",
    topics: ["Victim Support", "Emergency / Crisis", "Housing", "Parenting"],
    methods: ["Phone", "In person"],
    phone: "1-877-977-0007",
    website: "https://willowplaceshelter.ca/",
    emergency: true,
  },
  {
    id: "ikwe",
    organization: "Ikwe-Widdjiitiwin",
    name: "Indigenous women’s crisis shelter",
    description: "Confidential shelter and culturally grounded support for women and children escaping violence.",
    topics: ["Victim Support", "Emergency / Crisis", "Housing", "Indigenous", "Parenting"],
    methods: ["Phone", "In person"],
    phone: "1-800-362-3344",
    website: "https://www.ikwe.ca/",
    emergency: true,
  },
  {
    id: "eia",
    organization: "Manitoba Families",
    providerType: "Government",
    name: "Employment and Income Assistance",
    description: "Financial help with basic and health needs plus employment supports for eligible Manitobans.",
    topics: ["Income Support", "Food / Basic Needs", "Housing", "Employment / Training", "Health"],
    methods: ["Phone", "In person", "Online"],
    phone: "204-948-4000",
    website: "https://www.gov.mb.ca/fs/eia/",
  },
  {
    id: "manitoba-start",
    organization: "Manitoba Start",
    name: "Newcomer employment services",
    description: "Career coaching, labour-market preparation and employer connections for newcomers.",
    topics: ["Newcomers", "Employment / Training", "Education"],
    phone: "204-944-8833",
    website: "https://manitobastart.com/",
  },
  {
    id: "immigrant-centre",
    organization: "Immigrant Centre Manitoba",
    name: "Settlement and language services",
    description: "Settlement assistance, language learning, nutrition support and community connections.",
    topics: ["Newcomers", "Education", "Community and Culture", "Food / Basic Needs"],
    phone: "204-943-9158",
    website: "https://www.icmanitoba.com/",
  },
  {
    id: "welcome-place",
    organization: "Manitoba Interfaith Immigration Council",
    name: "Welcome Place settlement support",
    description: "Settlement, housing and legal orientation for refugees and newcomers.",
    topics: ["Newcomers", "Housing", "Legal Advocacy", "Community and Culture"],
    phone: "204-977-1000",
    website: "https://miic.ca/",
  },
  {
    id: "ircom",
    organization: "Immigrant and Refugee Community Organization of Manitoba",
    name: "Newcomer family and housing programs",
    description: "Transitional housing, settlement, childcare, youth and community development programs.",
    topics: ["Newcomers", "Housing", "Parenting", "Youth / Young Adults", "Community and Culture"],
    phone: "204-943-8765",
    website: "https://ircom.ca/",
  },
  {
    id: "ofe",
    organization: "Opportunities for Employment",
    name: "Employment preparation and placement",
    description: "Skills assessment, job preparation, training and employer connections.",
    topics: ["Employment / Training", "Education", "Income Support"],
    phone: "204-925-3490",
    website: "https://www.ofe.ca/",
  },
  {
    id: "yes-manitoba",
    organization: "Youth Employment Services Manitoba",
    name: "Youth employment services",
    description: "Free employment counselling, job-search support and workshops for young people.",
    topics: ["Youth / Young Adults", "Employment / Training", "Education"],
    phone: "204-987-8661",
    website: "https://www.yesmb.ca/",
  },
  {
    id: "student-aid",
    organization: "Manitoba Student Aid",
    providerType: "Government",
    name: "Student financial assistance",
    description: "Loans, grants and repayment information for eligible post-secondary students.",
    topics: ["Education", "Income Support", "Youth / Young Adults"],
    methods: ["Phone", "Online"],
    phone: "204-945-6321",
    website: "https://www.edu.gov.mb.ca/msa/",
  },
  {
    id: "millennium-library",
    organization: "Winnipeg Public Library",
    providerType: "Government",
    name: "Millennium Library community services",
    description: "Free information, computers, learning programs, newcomer resources and community space.",
    topics: ["Education", "Community and Culture", "Newcomers", "Employment / Training"],
    phone: "204-986-6450",
    website: "https://wpl.winnipeg.ca/library/branchpages/branch.aspx?mid=mm",
  },
  {
    id: "ka-ni-kanichihk",
    organization: "Ka Ni Kanichihk",
    name: "Indigenous community programs",
    description: "Culturally grounded healing, education, employment, youth and family programs.",
    topics: ["Indigenous", "Community and Culture", "Education", "Employment / Training", "Youth / Young Adults"],
    phone: "204-953-5820",
    website: "https://kanikanichihk.ca/",
  },
  {
    id: "ma-mawi",
    organization: "Ma Mawi Wi Chi Itata Centre",
    name: "Indigenous family and community care",
    description: "Family support, youth programs, cultural connection, housing and crisis services.",
    topics: ["Indigenous", "Parenting", "Youth / Young Adults", "Housing", "Community and Culture"],
    phone: "204-925-0300",
    website: "https://www.mamawi.com/",
  },
  {
    id: "mount-carmel",
    organization: "Mount Carmel Clinic",
    providerType: "Health authority",
    name: "Community health and social services",
    description: "Primary care, mental health, Indigenous wellness, parenting and community programs.",
    topics: ["Health", "Mental Health / Addictions", "Indigenous", "Parenting", "Community and Culture"],
    phone: "204-582-2311",
    website: "https://www.mountcarmel.ca/",
  },
  {
    id: "norwest",
    organization: "NorWest Co-op Community Health",
    providerType: "Health authority",
    name: "Community health services",
    description: "Primary care, counselling, family violence, parenting and community development supports.",
    topics: ["Health", "Mental Health / Addictions", "Parenting", "Victim Support"],
    phone: "204-938-5900",
    website: "https://norwestcoop.ca/",
  },
  {
    id: "family-dynamics",
    organization: "Family Dynamics",
    name: "Family resource and counselling services",
    description: "Counselling, in-home family support, parenting programs and neighbourhood resources.",
    topics: ["Parenting", "Mental Health / Addictions", "Community and Culture", "Youth / Young Adults"],
    phone: "204-947-1401",
    website: "https://familydynamics.ca/",
  },
  {
    id: "the-link",
    organization: "The Link: Youth and Family Supports",
    name: "Youth crisis and family supports",
    description: "Crisis stabilization, shelter, housing, mental-health and family services for youth.",
    topics: ["Youth / Young Adults", "Emergency / Crisis", "Housing", "Mental Health / Addictions", "Parenting"],
    phone: "204-477-1804",
    website: "https://thelinkmb.ca/",
    emergency: true,
  },
  {
    id: "ray",
    organization: "Resource Assistance for Youth",
    name: "Youth drop-in, housing and employment",
    description: "Low-barrier basic needs, housing, mental health, employment and cultural supports for youth.",
    topics: ["Youth / Young Adults", "Homelessness", "Housing", "Food / Basic Needs", "Employment / Training"],
    phone: "204-783-5617",
    website: "https://rayinc.ca/",
  },
  {
    id: "huddle-broadway",
    organization: "Huddle Manitoba",
    providerType: "Health authority",
    name: "Huddle Broadway integrated youth services",
    description: "Free health, mental-health, substance-use, employment and peer support for ages 12–29.",
    topics: ["Youth / Young Adults", "Health", "Mental Health / Addictions", "Employment / Training"],
    phone: "204-228-6387",
    website: "https://huddlemanitoba.ca/location/huddle-broadway/",
  },
  {
    id: "kids-help-phone",
    organization: "Kids Help Phone",
    name: "24/7 youth crisis support",
    description: "Confidential phone, text and online mental-health support for young people.",
    topics: ["Youth / Young Adults", "Emergency / Crisis", "Mental Health / Addictions", "Victim Support"],
    methods: ["Phone", "Online"],
    serviceArea: "Winnipeg and Canada-wide",
    phone: "1-800-668-6868",
    website: "https://kidshelpphone.ca/",
    emergency: true,
  },
  {
    id: "north-end-womens",
    organization: "North End Women’s Centre",
    name: "Women’s resource and community programs",
    description: "Drop-in, basic needs, counselling, housing, employment and cultural supports.",
    topics: ["Community and Culture", "Food / Basic Needs", "Housing", "Victim Support", "Indigenous"],
    phone: "204-589-7347",
    website: "https://newcentre.org/",
  },
  {
    id: "arts-accessability",
    organization: "Arts AccessAbility Network Manitoba",
    name: "Disability arts network",
    description: "Accessible arts programming, professional development and community connection for artists with disabilities.",
    topics: ["Accessibility", "Community and Culture", "Education"],
    methods: ["Online", "In person"],
    phone: "204-336-2366",
    website: "https://aanm.ca/",
  },
];

const organizationsById = new Map<string, Organization>();

const programs: Program[] = seeds.map((seed) => {
  const organizationId = seed.organization
    .toLocaleLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
  if (!organizationsById.has(organizationId)) {
    organizationsById.set(organizationId, {
      id: organizationId,
      name: seed.organization,
      providerType: seed.providerType ?? "Nonprofit",
      website: seed.website,
      sourceUrls: [seed.website],
    });
  }

  return {
    id: seed.id,
    organizationId,
    organization: seed.organization,
    name: seed.name,
    description: seed.description,
    topics: seed.topics,
    methods: seed.methods ?? ["In person", "Phone"],
    serviceArea: seed.serviceArea ?? "Winnipeg",
    eligibility: seed.eligibility ?? "See provider for current eligibility",
    ageRange: seed.ageRange ?? "All applicable ages",
    languages: seed.languages ?? ["English"],
    cost: seed.cost ?? "Free or publicly funded",
    intake: seed.intake ?? "Call or visit the official website before attending",
    phone: seed.phone,
    website: seed.website,
    status: "Active",
    verifiedAt,
    sourceUrls: [seed.website],
    emergency: seed.emergency ?? false,
  };
});

const publicLocations: Array<[string, string, string, number, number, string]> = [
  ["crc-raam", "Crisis Response Centre", "817 Bannatyne Avenue, Winnipeg", 49.9034, -97.1585, "Mon–Sat; see current walk-in schedule"],
  ["riverpoint-raam", "River Point Centre", "146 Magnus Avenue, Winnipeg", 49.9197, -97.1358, "Weekdays; see current walk-in schedule"],
  ["ahwc-raam", "Aboriginal Health and Wellness Centre", "181 Higgins Avenue, Winnipeg", 49.9031, -97.1348, "Tue–Sat; see current walk-in schedule"],
  ["klinic-crisis", "Klinic Community Health", "167 Sherbrook Street, Winnipeg", 49.8829, -97.1595, "Crisis phone support 24/7"],
  ["mainstreet-shelter", "Main Street Project", "637 Main Street, Winnipeg", 49.9033, -97.1362, "Daily day and overnight services"],
  ["mainstreet-withdrawal", "Withdrawal Management", "75 Martha Street, Winnipeg", 49.9025, -97.1324, "24-hour residential program; intake required"],
  ["riverpoint-withdrawal", "River Point Centre", "146 Magnus Avenue, Winnipeg", 49.9197, -97.1358, "24-hour residential program; intake required"],
  ["siloam", "Siloam Mission", "300 Princess Street, Winnipeg", 49.9056, -97.1434, "Daily; program hours vary"],
  ["centre-hope", "Winnipeg Centre of Hope", "180 Henry Avenue, Winnipeg", 49.9019, -97.1425, "24-hour shelter programming"],
  ["winnipeg-harvest", "Harvest Manitoba", "1085 Winnipeg Avenue, Winnipeg", 49.9243, -97.1789, "Weekdays; call for a food appointment"],
  ["meals-wheels", "Meals on Wheels Winnipeg", "174 Hargrave Street, Winnipeg", 49.8914, -97.1431, "Office hours weekdays"],
  ["a-o-support", "A & O Support Services", "200–280 Smith Street, Winnipeg", 49.8948, -97.1411, "Weekdays"],
  ["rainbow-resource", "Rainbow Resource Centre", "545 Broadway, Winnipeg", 49.8865, -97.1511, "Program hours vary"],
  ["sunshine-house", "Sunshine House", "646 Logan Avenue, Winnipeg", 49.9145, -97.1484, "Drop-in and mobile schedules vary"],
  ["nine-circles", "Nine Circles", "705 Broadway, Winnipeg", 49.8842, -97.1598, "Mon–Fri 9:00–17:00"],
  ["manitoba-possible", "Manitoba Possible", "825 Sherbrook Street, Winnipeg", 49.9044, -97.1575, "Weekdays"],
  ["seed-financial", "SEED Winnipeg", "80 Salter Street, Winnipeg", 49.9082, -97.1389, "Appointment and program schedules vary"],
  ["legal-aid", "Legal Aid Manitoba", "100–287 Broadway, Winnipeg", 49.8879, -97.1426, "Weekdays"],
  ["victim-services", "Manitoba Justice", "405 Broadway, Winnipeg", 49.8864, -97.1462, "Weekdays; crisis supports by phone"],
  ["eia", "EIA Winnipeg Intake", "111 Rorie Street, Winnipeg", 49.8984, -97.1358, "Weekdays"],
  ["manitoba-start", "Manitoba Start", "271 Portage Avenue, Winnipeg", 49.8951, -97.1419, "Weekdays"],
  ["immigrant-centre", "Immigrant Centre Manitoba", "100 Adelaide Street, Winnipeg", 49.8981, -97.1391, "Weekdays"],
  ["welcome-place", "Welcome Place", "521 Bannatyne Avenue, Winnipeg", 49.9011, -97.1512, "Weekdays"],
  ["ircom", "IRCOM House", "95 Ellen Street, Winnipeg", 49.9014, -97.1501, "Program hours vary"],
  ["ofe", "Opportunities for Employment", "300–294 Portage Avenue, Winnipeg", 49.8952, -97.1424, "Weekdays"],
  ["yes-manitoba", "Youth Employment Services", "614–294 Portage Avenue, Winnipeg", 49.8952, -97.1424, "Weekdays"],
  ["millennium-library", "Millennium Library", "251 Donald Street, Winnipeg", 49.8916, -97.1425, "Library hours vary"],
  ["ka-ni-kanichihk", "Ka Ni Kanichihk", "455 McDermot Avenue, Winnipeg", 49.9008, -97.1504, "Program hours vary"],
  ["ma-mawi", "Ma Mawi Wi Chi Itata Centre", "445 King Street, Winnipeg", 49.9048, -97.1392, "Program hours vary"],
  ["mount-carmel", "Mount Carmel Clinic", "886 Main Street, Winnipeg", 49.9147, -97.1298, "Clinic and program hours vary"],
  ["norwest", "NorWest Co-op", "785 Keewatin Street, Winnipeg", 49.9391, -97.1938, "Clinic and program hours vary"],
  ["family-dynamics", "Family Dynamics", "401–393 Portage Avenue, Winnipeg", 49.8944, -97.1466, "Weekdays"],
  ["the-link", "The Link", "175 Mayfair Avenue, Winnipeg", 49.8784, -97.1358, "Crisis services available 24/7"],
  ["ray", "Resource Assistance for Youth", "125 Sherbrook Street, Winnipeg", 49.8844, -97.1589, "Drop-in hours vary"],
  ["huddle-broadway", "Huddle Broadway", "533 Broadway, Winnipeg", 49.8866, -97.1504, "Youth-friendly service hours vary"],
  ["north-end-womens", "North End Women’s Centre", "394 Selkirk Avenue, Winnipeg", 49.9129, -97.1399, "Weekday drop-in and program hours"],
];

const locations: ServiceLocation[] = publicLocations.map(
  ([programId, name, address, latitude, longitude, hours], index) => ({
    id: `public-${index + 1}`,
    programId,
    visibility: "Public",
    name,
    address,
    latitude,
    longitude,
    accessibility: "Contact the provider for current access details",
    hours,
  }),
);

locations.push(
  {
    id: "confidential-willow",
    programId: "willow-place",
    visibility: "Confidential",
    name: "Confidential shelter location",
    accessibility: "Discuss access needs by phone",
    hours: "Crisis line available 24/7",
  },
  {
    id: "confidential-ikwe",
    programId: "ikwe",
    visibility: "Confidential",
    name: "Confidential shelter location",
    accessibility: "Discuss access needs by phone",
    hours: "Crisis line available 24/7",
  },
  ...programs
    .filter((program) => !locations.some((location) => location.programId === program.id))
    .map((program, index) => ({
      id: `service-area-${index + 1}`,
      programId: program.id,
      visibility: "Service area" as const,
      name: `${program.serviceArea} service`,
      accessibility: "Contact the provider for access details",
      hours: program.emergency ? "Emergency access varies; call first" : "See official schedule",
    })),
);

export const directoryData: DirectoryData = {
  organizations: [...organizationsById.values()],
  programs,
  locations,
};
